import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AppHeader from "@/components/AppHeader";
import "./globals.css";
import TanStackProvider from "@/components/TanStackProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <TanStackProvider>
          <div style={{ backgroundColor: "lightcoral", padding: 8 }}>
            <AppHeader />
            {/* <h1>Root layout (app/layout.tsx)</h1> */}
            {children}
            {modal}
          </div>
        </TanStackProvider>
      </body>
    </html>
  );
}

//gallery/[imageId]
